tracker = dict(
    type='TrackingByDetection',
    detector=dict(
        include='./detector/mmdetection/faster_rcnn_x101_64x4d_fpn_1x_coco.py'
    ),
    encoders=[
        dict(
            include='./encoder/dgnet.py'
        ),
    ],
    matcher=dict(
        type='HungarianMatcher',
        metric=dict(
            type='CosineMetric',
            encoding='dgnet',
        ),
        threshold=0.8
    ),
    predictor=None,
)
